# Generated by Django 5.0.6 on 2024-07-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_user_subscription_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="owner",
            new_name="payments",
        ),
    ]
