# Generated by Django 5.0.6 on 2024-07-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Цена на подписку"
            ),
        ),
    ]
