# Generated by Django 5.0.6 on 2024-07-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=500, verbose_name="Текст комментария"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата создания комментария"
            ),
        ),
    ]
