# Generated by Django 5.0.6 on 2024-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_options_alter_comment_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="price",
        ),
        migrations.AddField(
            model_name="blog",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Платный контент"),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
