# Generated by Django 5.0.6 on 2024-07-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_blog_price_blog_is_premium_delete_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("can_edit_title", "Can edit title"),
                    ("can_edit_content", "Can edit content"),
                ],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
